### ISSUE TITLE
First Six + Last Four from Offline Transaction

### ISSUE THREAD

**Issue by pthomson** [clover/remote-pay-windows#43]
when the Clover does not have an active network connection, it will Approve the Sale Request and return the Offline attribute as True (and the CardType attribute such as VISA) which is great. But when this happens it does not return the First Six or Last Four from the card account that was used by the customer on the device. These two values would be extremely useful information for us to retain in our Semi-Integration applications so that we can have a human readable reference to the Transaction beyond the Clover generated OrderId that can be cross referenced and verified back to the customer. Thank you!

**Comment by JoelMc-Clover** [comment]
Thanks! I've added this issue into our internal systems for evaluation and followup. 
Hopefully you are able to leverage the external payment id and returned clover payment id to get around the lack of this information, but we'd love to provide everything we can for convenient use.
