### ISSUE TITLE
Integrate CloverExamplePOS application to USB Pay Disply

### ISSUE THREAD

**Issue by ghost** [clover/remote-pay-windows#7]
Hi

Clover mini connected to my laptop using USB cable. when i run the CloverExamplePOS application in my laptop and select the USB cable option, i got the not connected status in the lable.

When i connect the USB cable between Clover mini and laptop, in clover mini display shows 
 Welcome to 
XXXXX XXXXXX

Attached screen shot for not connected status.

Am i doing correct or not? Can you give the step by step method
![notconnected](https://cloud.githubusercontent.com/assets/13886185/15124372/75d4ed66-1645-11e6-8cf1-c715ca0c26c5.png)

**Comment by blake-clover** [comment]
When you installed, did you install the REST and/or WebSocket Service? If so, it can conflict with the direct USB connection. If you can either uninstall or stop those Windows services, it should work. We have an issue to fix that bug in the installer, as the intent is to run in one of the three modes, not all three.

**Comment by rizqi101** [comment]
I'm having the same experience. I uninstalled the services but still no luck.  i checked the device manager, maybe this can give a clue.
![clover-device-manager](https://cloud.githubusercontent.com/assets/2237714/15462524/2d62165c-2078-11e6-9712-616f65023bc3.png)

Im running windows 7 Ultimate 64bit. Thank you.

**Comment by ghost** [comment]
Hi

Problem solved, i am able to connect now. 
Thanks

**Comment by rizqi101** [comment]
Can you share your solution please?
